configfile: "config/config.yaml"

include: "rules/extend-graph-chrom.smk"
include: "rules/analyze-graph.smk"

samples = [s for s in config["reads"].keys()]

print('samples', samples)

rule all:
	input:
		"results/minigraph/minigraph-extended_all.gfa",
		expand("results/statistics/bubbles/{version}_all_bubbles.tsv", version=["original", "extended"]),
		expand("results/statistics/mapping/{version}_all_{sample}_{method}.stats", version=["original", "extended"], method=["minigraph"],  sample = samples),
		"results/statistics/plots/all_bubbles.pdf"
