configfile: "config/config.yaml"

include: "rules/extend-graph-chrom.smk"
include: "rules/analyze-graph.smk"

chromosomes = [i for i in config["minigraph_gfa"].keys()]

samples = [s for s in config["reads"].keys()]

print('samples', samples)

rule all:
	input:
		expand("results/minigraph/minigraph-extended_{chrom}.gfa", chrom=chromosomes),
		expand("results/statistics/bubbles/{version}_{chrom}_bubbles.tsv", version=["original", "extended"], chrom=chromosomes),
		expand("results/statistics/mapping/{version}_all_{sample}_{method}.stats", version=["original", "extended"], method=["minigraph", "graphaligner"],  sample = samples)
