# callsets with variants to be added to the graph
callset_vcfs:
 sniffles: "/gpfs/project/projects/medbioinf/users/ebler/long-read-1kg/data/population-vcfs/delins.sniffles.hg38.liftedT2T.13Nov2023.nygc.vcf.gz"
 delly: "/gpfs/project/projects/medbioinf/users/ebler/long-read-1kg/data/population-vcfs/delins.delly.hg38.liftedT2T.13Nov2023.nygc.vcf.gz"
 SVarp: "/gpfs/project/projects/medbioinf/users/ebler/long-read-1kg/prepare-SVarp-callset/SVarp-hg38/merged-vcfs/SVarp-hg38_biallelic_truvari_filtered.vcf.gz"

# minigraph GFA of full genome.
minigraph_gfa: "/gpfs/project/projects/medbioinf/data/share/globus/1000g-ont/rgfa/chm13-90c.r518_tagged_withseq.gfa"

# reference sequence underlying the callsets
reference: "/gpfs/project/projects/medbioinf/users/ebler/long-read-1kg/data/1KG_ONT_VIENNA_hg38.fa"

# BED to mask reference
mask: "/gpfs/project/projects/medbioinf/users/ebler/long-read-1kg/data/hg38-ucsc-centromers.bed"

# path to gaftools executable
gaftools: "/gpfs/project/projects/medbioinf/projects/1000g-ont/gaftools"


#######################################################
# optional arguments (needed for evaluation only)
####################################################### 

# reads of the samples to be used for validation. Files must be in SAM/BAM/CRAM format.
# # reads must be aligned to the same reference as listed above.
reads:
 HG00513: "/gpfs/project/projects/medbioinf/users/ebler/long-read-1kg/data/crams/HG00513.hg38.cram"
