# callsets with variants to be added to the graph
callset_vcfs:
 caller1: "/path/to/callset1.vcf.gz"
 caller2: "path/to/callset2.vcf.gz"


# minigraph GFA of full genome.
minigraph_gfa: "/path/to/minigraph.gfa"

# reference sequence underlying the callsets
reference: "/path/to/reference.fa"

# BED to mask reference
mask: "/path/to/centromeres.bed"

# path to gaftools executable / gaftools command
gaftools: "/path/to/gaftools"


#######################################################
# optional arguments (needed for evaluation only)
####################################################### 

# reads of the samples to be used for validation. Files must be in SAM/BAM/CRAM format.
# # reads must be aligned to the same reference as listed above.
reads:
 HG00513: "/path/to/reads.cram"
