

intersections:
  "A": 
        table: "data/A_intersection_all.tsv"
        present: "in_HGSVC in_pav_A in_sniffles2_A"
        absent: "in_1KG-ONT"
        baseline: "in_pav_A in_sniffles2_A"
  "B":
        table: "data/B_intersection_all.tsv"
        present: "in_HGSVC in_pav_B in_sniffles2_B"
        absent: "in_1KG-ONT"
        baseline: "in_pav_B in_sniffles2_B"
  "C":
        table: "data/C_intersection_all.tsv"
        present: "in_HGSVC in_pav_C in_sniffles2_C"
        absent: "in_1KG-ONT"
        baseline: "in_pav_C in_sniffles2_C"
  "D":
        table: "data/D_intersection_all.tsv"
        present: "in_HGSVC in_pav_D in_sniffles2_D"
        absent: "in_1KG-ONT"
        baseline: "in_pav_D in_sniffles2_D"


graph_bubbles: /gpfs/project/projects/medbioinf/users/ebler/long-read-1kg/graph-augmentation/results/statistics/bubbles/extended_all_bubbles.tsv
panel_vcf: /gpfs/project/projects/medbioinf/data/share/globus/hhu-1000g-ont/giggles-genotyping/augmented-graph/prepared-panel/giggles-ready_multiallelic.vcf.gz
panel_biallelic_vcf: /gpfs/project/projects/medbioinf/data/share/globus/hhu-1000g-ont/giggles-genotyping/augmented-graph/prepared-panel/giggles-ready_biallelic.vcf.gz 
unfiltered_genotypes_vcf: /gpfs/project/projects/medbioinf/data/share/globus/hhu-1000g-ont/giggles-genotyping/augmented-graph/multisample-genotypes/biallelic.ac0-filtered.vcf.gz
filtered_genotypes_vcf: /gpfs/project/projects/medbioinf/data/share/globus/hhu-1000g-ont/genotype-filtering/augmented/biallelic.filtered.all-samples.vcf.gz


beds:
  repeats: "chm13-repeat-masker-merged.bed"
  segdups: "chm13-segdups-merged.bed"
